config/routes.rb
Rebulba::Application.routes.draw do
  resources :users, except: [:index] do
    resources :followings, only: [:create]
  end

  resources :posts, only: [:create, :update, :destroy, :show] do
    resources :comments, only: [:create, :update]
    resources :likes, only: [:create]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :followings, only: [:destroy]
  
  resources :notifications, only: [:show, :destroy]


  root to: "sessions#new"
  
  namespace :api, :defaults => { :format => :json } do

    resources :posts, only: [:index, :create, :update, :destroy, :show] do
      
    end
    resources :likes, only: [:create]
    
    resources :comments, only: [:create, :update, :destroy]
		
		resources :likes, only: [:destroy]
  end
  
  get 'auth/facebook/callback', to: 'sessions#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, presence: true
  before_create :set_likes

  belongs_to :user
  has_many  :likes, as: :likeable, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy, inverse_of: :post
  
  def set_likes
    self.likes_count = 0
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def create
    @post = current_user.posts.new(post_params)
    @post.likes_count = 0
    
    if @post.save

      render json: @post
    else
      render json: {}, status: :unprocessible_entity
    end
  end

  def index
    @posts = current_user.posts
    render json: @posts.to_json(:include => :user)
    # @feed_posts = current_user.genereate_feed_posts(5)
#     render json: @feed_posts

  end

  def show
    @post = Post.find(params[:id])
    render partial: "posts/post.json", locals: { post: @post }
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      render json: @post
    else
      flash.now[:errors] = @post.errors.full_messages
      render json: @post.errors.full_messages, status: :unprocessible_entity
    end

  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy if post
    render json: {}
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :likes_count)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.likes_count = 0
    if @post.save

      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to current_user
    end
  end

  def index
    @posts = current_user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to current_user
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to current_user
    end

  end

  def destroy
    post = current_user.posts.find(params[:id]) 
    post.destroy if post
    redirect_to user_url(current_user)
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/views/layouts/post/_deletepost.html.erb
<form class="delete-post" data-id="<%= post.id %>"> action="<%= post_url(post) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <%= auth_token %>
  <input type="submit" value="delete">
</form>

app/views/layouts/post/_editpost.html.erb
<div class="post-form">
	<form action="<%= post_url(post) %>" method="post">
	  <input type="hidden" name="_method" value="put">

	  <%= auth_token %>

	  <%= post_form("update post", post.title, post.body) %>

	</form>
</div>

app/views/layouts/post/_post.html.erb
<section id="feed" class="posts group">
	<% if false %>
	  <% feed_posts.each do |post| %>

	  <article class="post">
	  
		  <%= render partial: "layouts/post/postoptions", locals: {post: post} %>
	  
	    <div class="post-thumb">
	      <a href="#"><img src="<%= @user.avatar %>" width="54" height="54" alt=""></a>
	    </div>
		<div class="post-content">
		    <header class="post-header group">
				<h4><%= link_to post.user.username, user_url(post.user) %><h4>
				<h3><%= link_to post.title, post_url(post.id), method: :get %></h3>
		
		      <div class="post-header-info">  
		        <time><%= post.updated_at %></time>
		      </div>
		    </header>
		     <p class="post-body"><%= post.body %></p>
				 <nav class="post-bottom-nav">
					 <a class="likes" href="#"><%= post.likes.count.to_s + " likes" %></a>
				 
				</nav>
		</div>

	    <div class="comment">
	      <%= render partial: "layouts/comment/postcomments", locals: {post: post} %>
	    </div>

	
	  </article>

	  <% end %>
	<% end %>
  
</section>

app/views/layouts/post/_postoptions.html.erb
<div class="post-options">

<% if params["id"].to_i == current_user.id %>

  <%= render partial: "layouts/post/deletepost", locals: {post: post} %>

  <%= render partial: "layouts/post/editpost", locals: {post: post} %>

<% else %>

  <% if post.likers.include?(current_user) %>
    <%= button_to "unlike", like_url(post.likes.where("user_id = ?", current_user.id).first.id), method: :delete %>
  <% else %>
    <%= button_to "like", post_likes_url(post.id), method: :post %>

  <% end %>

<% end %>
</div>