config/routes.rb
Rebulba::Application.routes.draw do
  resources :users, except: [:index] do
    resources :followings, only: [:create]
  end

  resources :posts, only: [:create, :update, :destroy, :show] do
    resources :comments, only: [:create, :update]
    resources :likes, only: [:create]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :followings, only: [:destroy]
  
  resources :notifications, only: [:show, :destroy]


  root to: "sessions#new"
  
  namespace :api, :defaults => { :format => :json } do

    resources :posts, only: [:index, :create, :update, :destroy, :show] do
      
    end
    resources :likes, only: [:create]
    
    resources :comments, only: [:create, :update, :destroy]
		
		resources :likes, only: [:destroy]
  end
  
  get 'auth/facebook/callback', to: 'sessions#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :post, inverse_of: :comments
  has_many :likes, as: :likeable, dependent: :destroy

  belongs_to :comment_sender, inverse_of: :sent_comments,
  class_name: "User",
  foreign_key: :user_id

  has_many :likers, through: :likes, source: :user
  
  has_many :notifications, as: :notifiable, inverse_of: :notifiable, dependent: :destroy

  after_commit :set_notification, on: [:create]
  
  def set_notification
    notification = self.notifications.unread.event(:comment_on_post).new
    notification.user = self.post.user
    notification.save
    
    
    self.post.comments.each do |comment|
      next if comment == self
      n = comment.notifications.unread.event(:comment_after_comment).new
      n.user = comment.comment_sender
      n.save
    end
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    
    if @comment.save

      render json: @comment
    else
      render json: {}, status: :unprocessible_entity
    end
  end
  
  def destroy
    comment = Comment.find(params[:id])
    if comment.comment_sender == current_user || comment.post.user == current_user
      comment.destroy
    end
    render json: {}
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.comment_sender == current_user
      if @comment.update_attributes(comment_params)
        render json: @comment
      else
        render json: {}, status: :unprocessible_entity
      end
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    comment = current_user.sent_comments.new(comment_params)
    post = Post.find(params[:post_id])
    comment.post = post
    if comment.save

      redirect_to(:back)
    else
      flash.now[:errors] = comment.errors.full_messages
      redirect_to current_user
    end
  end

  def update
    comment = current_user.sent_comments.find(params[:id])
    comment.update(comment_params)
    redirect_to(:back)
  end

  def destroy
    comment = current_user.sent_comments.find(params[:id]) ||
    comment = current_user.comments.find(params[:id])
    comment.destroy
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/layouts/comment/_delete.html.erb
  <form action="<%= comment_url(comment.id) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= auth_token %>
    <input type="submit" value="delete">
  </form>

app/views/layouts/comment/_edit.html.erb
<form action="<%= post_comment_url(post.id, comment.id) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>

  <%= comment_form("update comment") %>
</form>

app/views/layouts/comment/_new.html.erb
<div class="new-comment-wrap">
  <form action="<%= post_comments_url(post.id) %>" method="post">
    <%= auth_token %>
    <%= comment_form("Add") %>
  </form>
</div>

app/views/layouts/comment/_postcomments.html.erb
<section class="comments-wrap">
  <% post.comments.each do |comment| %>
	
	<article>
	      <p><%= comment.body %><p>
	      <%= comment.comment_sender.username %>
	      <time><%= comment.updated_at %></time>
	      <%= comment.likes.count.to_s + " likes" %>

	      <% if comment.user_id == current_user.id %>
	        <%= render partial: "layouts/comment/edit", locals: {post: post, comment: comment} %>
	      <% else %>
	        <% if comment.likers.include?(current_user) %>
	          <%= button_to "unlike", like_url(comment.likes.where("user_id = ?", current_user.id).first.id), method: :delete %>
	        <% else %>
	          <%= button_to "like", comment_likes_url(comment.id), method: :post %>

	        <% end %>
	      <% end %>


	      <% if comment.user_id == current_user.id || post.user_id == current_user.id %>
	        <%= render partial: "layouts/comment/delete", locals: {comment: comment} %>
	      <% end %>
		  
	</article>

		 <% end %>
		
	
	
</section>

<%= render partial: "layouts/comment/new", locals: {post: post} %>