config/routes.rb
Rebulba::Application.routes.draw do
  resources :users, except: [:index] do
    resources :followings, only: [:create]
  end

  resources :posts, only: [:create, :update, :destroy, :show] do
    resources :comments, only: [:create, :update]
    resources :likes, only: [:create]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :followings, only: [:destroy]
  
  resources :notifications, only: [:show, :destroy]


  root to: "sessions#new"
  
  namespace :api, :defaults => { :format => :json } do

    resources :posts, only: [:index, :create, :update, :destroy, :show] do
      
    end
    resources :likes, only: [:create]
    
    resources :comments, only: [:create, :update, :destroy]
		
		resources :likes, only: [:destroy]
  end
  
  get 'auth/facebook/callback', to: 'sessions#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :make_url_image
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://s3.amazonaws.com/rebulba_dev/users/avatars/000/000/007/original/puppy.jpg?1398551275"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]
  
  include Rails.application.routes.url_helpers

  before_validation :ensure_session_token
  attr_reader :password

  has_many :posts,
  class_name: "Post",
  foreign_key: :user_id,
  primary_key: :id,
  inverse_of: :user,
  dependent: :destroy

  has_many :comments, through: :post, source: :user

  has_many :sent_comments,
  class_name: "Comment",
  foreign_key: :user_id,
  primary_key: :id,
  inverse_of: :comment_sender

  has_many :inbound_followings,
  class_name: "Following",
  foreign_key: :followee_id,
  primary_key: :id,
  dependent: :destroy

  has_many :outbound_followings,
  class_name: "Following",
  foreign_key: :follower_id,
  primary_key: :id,
  dependent: :destroy

  has_many :people_he_follows, through: :outbound_followings, source: :followee
  has_many :followers, through: :inbound_followings, source: :follower

  has_many :likes
  has_many :comments, through: :posts, source: :comments
  
  has_many :notifications, inverse_of: :user, dependent: :destroy

  def self.generate_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_token!
    self.token = User.generate_token
    self.save!
    self.token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user.try(:is_password?, password) ? user : nil
  end

  def is_password?(undigested_password)
    BCrypt::Password.new(self.password_digest).is_password?(undigested_password)
  end

  def password=(undigested_password)
    if undigested_password.present?
      @password = undigested_password
      self.password_digest = BCrypt::Password.create(undigested_password)
    end
  end

  def ensure_session_token
    self.token ||= User.generate_token
  end

  def generate_feed_posts(num=5)
    #optimize to include comments, likes, and all on query... n+1
    # self.people_he_follows.includes(:posts).limit(num).map(&:posts).flatten
    
    self.people_he_follows.includes(:posts).includes([:comments, :likes]).map(&:posts).flatten
  end
  
  
  
  def make_url_image
    if self.avatar.class == String
      self.avatar = open(self.avatar, allow_redirections: :safe)
    end
  end
  
  
  # here and in notifications: factor out
  def default_url_options
    options = {}
    options[:host] = Rails.env.production? ? "www.rebulba.com" : "localhost:3000"
    options
  end
  
  def show_url
    users_url + "/#{self.id}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in
  skip_before_action :require_logged_in, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to current_user
      #msg = UserMailer.welcome_email(@user)
      #msg.deliver!
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    
    @new_post = Post.new
    @new_following = Following.new
    
    @feed_posts = @user.generate_feed_posts if @user == current_user

    @user_posts = @user.posts.includes(:comments => [:likes, :comment_sender], :likes => [:user])
    @own_page = (current_user == @user)

  end

  def edit
    @user = User.new
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to current_user
    else
      flash.now[:errors] = current_user.errors.full_messages
      render :edit
    end
  end

  def destroy
    if current_user.id > 6
      current_user.destroy
      redirect_to new_session_url
    else
      flash.now[:errors] = ["you didn't create this user!"]
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :avatar)
  end

end

app/views/users/edit.html.erb
<form class="edit-user" action="<%= user_url(current_user) %>" method="post" enctype="multipart/form-data">
  <input type="hidden" name="_method" value="put">
	
	<div class="edit-profile-title">
  	<h1>Edit Profile</h1>
	</div>
  <%= auth_token %>

  <%= user_form("Update Profile", current_user.username, current_user.email) %>
</form>


<%= button_to "Delete My Account", user_url(current_user), method: :delete %>

app/views/users/new.html.erb
<div class="welcome">
	<h1>Welcome to Rebulba</h1>
	<h4>A clone of tumblr---with more puppies</h4>
</div>
<form class="user-form" action="<%= users_url %>" method="post" enctype="multipart/form-data">
  <%= auth_token %>

  <%= user_form("Sign Up") %>
</form>
<h3><%= link_to "--Visit Sign In Page--", new_session_url %></h3>

<h3><a href="/auth/facebook">Sign in/up with Facebook</a></h3>

app/views/users/show.html.erb
<div class="content group">

  <section class="profile">
  
    <% if @user.avatar %>
      <img src="<%= @user.avatar.url %>">
    <% else %>
      <img src="http://s3.amazonaws.com/rebulba_dev/users/avatars/000/000/007/original/puppy.jpg?1398551275">

    <% end %>
		
		<div class="add-delete-follower">
	  	<% if current_user.id.to_s != params[:id] %>
	      <% if current_user.people_he_follows.include?(@user) %>
	        
	      <% else %>
	        	<%= render partial: "layouts/following/new" %>
	      <% end %>
			<% end %>
		</div>
 	 	
		<nav class="profile-side-nav">
			<form action="<%= session_url %>" class="button_to sign-out" method="post">
				<input name="_method" type="hidden" value="delete">
				<input type="submit" value="Sign Out">
				<%= auth_token %>
			</form>
			
			<li class="home-link"><%= link_to "Home", user_url(current_user.id) %></li>

			<button class="side-nav-button" id="followings">Following (<%= @user.people_he_follows.count %>)</button>
			
			<div class="following-wrap">
		    <div class="following">
		      <%= render partial: "layouts/following/followings", locals: {user: @user} %>	
		    </div>
			</div>
			
			<button class="side-nav-button" id="followers">Followers (<%= @user.followers.count %>) </button>
			
			<div class="followers-wrap">
		    <div class="followers">
		      <%= render partial: "layouts/following/followers", locals: {user: @user} %>	
		    </div>
			</div>
			
			<% if @own_page %>
				<button class="side-nav-button" id="notifications">Notifications (<%= 				current_user.notifications.unread.count %>)</button>
			<% end %>

		</nav>

		<% if @own_page %>
			<div class="notifications-wrap">
				<ul class="notifications-list">
				<% current_user.notifications.each do |note| %>
					<% if note.is_read %>

					<% else %>
						<li class="unread group">
							<form action="<%= notification_url(note) %>" method="post">
								<%= auth_token %>
								<input type="hidden" name="_method" value="delete">
								<button>&times;</button>
							</form>
							<a href="<%= notification_url(note) %>"><%= note.text %></a>
							<time><%= time_ago_in_words(note.created_at) %></time>
						</li>
					<% end %>
				<% end %>
			</ul>
		</div>
	<% end %>
  </section>

	  <% if @own_page %>
	    <section class="feed group">
				<div class="user-posts group">
				  <%= render partial: "layouts/post/post", locals: {feed_posts: @user_posts} %>
				<div>
				<div class="feed-posts group">
					<h1><%= @user.username + "\'s page" %></h1>

					<div class="post-form group">
	
					  <form action="<%= posts_url %>" method="post">
						  <h3> New Post </h3>
					    <%= auth_token %>

					    <%= post_form("submit post") %>
					  </form>
					</div>
				  <h3>My Feed</h3>
				  <%= render partial: "layouts/post/post", locals: {feed_posts: @feed_posts} %>
				</div>
	    </section>
	  
		<% else %>
		  <section class="show-page group">
		
		    <%= render partial: "layouts/post/post", locals: {feed_posts: @user_posts} %>
		  </section>
	  <% end %>
	
</div>

<script type="application/json" id="bootstrapped_user_json">
  { "current_user": <%= current_user.to_json.html_safe %>,
		"user": <%= @user.to_json.html_safe %>, 
		"feed-posts": <%= render(partial: "posts/posts.json", locals: { posts: @feed_posts}).html_safe %>,
  	"user-posts": <%= render(partial: "posts/posts.json", locals: { posts: @user_posts}).html_safe %>,
		"ownPage": <%= @own_page %>,
		"home_url": <%= current_user.show_url.to_json.html_safe %>,
		"edit_url": <%= edit_user_url(current_user).to_json.html_safe %>
	}
</script>

<script>
	$(document).ready(function(){
		
		$("#notifications").on("click", function(){
			$("#followings").removeClass("active-button")
			$("#followers").removeClass("active-button")
			
			$("#notifications").addClass("active-button")
			
			if ($(".notifications-wrap").hasClass("visible")){
				$(".notifications-wrap").removeClass("visible")
				$("#notifications").removeClass("active-button")
			} else {
				$(".notifications-wrap").addClass("visible")
			};
			
			$(".following-wrap").removeClass("visible")
			$(".followers-wrap").removeClass("visible")
			
		});
		
		$("#followings").on("click", function(){
			$("#notifications").removeClass("active-button")
			$("#followers").removeClass("active-button")
			
			$("#followings").addClass("active-button")
			
			if ($(".following-wrap").hasClass("visible")){
				$(".following-wrap").removeClass("visible")
				$("#followings").removeClass("active-button")
			} else {
				$(".following-wrap").addClass("visible")
			};
			
			$(".followers-wrap").removeClass("visible")
			$(".notifications-wrap").removeClass("visible")
		});
		
		$("#followers").on("click", function(){
			$("#notifications").removeClass("active-button")
			$("#followings").removeClass("active-button")
			
			$("#followers").addClass("active-button")
			if ($(".followers-wrap").hasClass("visible")){
				$(".followers-wrap").removeClass("visible")
				$("#followers").removeClass("active-button")
			} else {
				$(".followers-wrap").addClass("visible")
			};
			
			$(".following-wrap").removeClass("visible")
			$(".notifications-wrap").removeClass("visible")
			
		});

		
	  Rebulba.initialize();
	});
	


	
</script>