config/routes.rb
Rebulba::Application.routes.draw do
  resources :users, except: [:index] do
    resources :followings, only: [:create]
  end

  resources :posts, only: [:create, :update, :destroy, :show] do
    resources :comments, only: [:create, :update]
    resources :likes, only: [:create]
  end

  resources :comments, only: [] do
    resources :likes, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]
  resources :followings, only: [:destroy]
  
  resources :notifications, only: [:show, :destroy]


  root to: "sessions#new"
  
  namespace :api, :defaults => { :format => :json } do

    resources :posts, only: [:index, :create, :update, :destroy, :show] do
      
    end
    resources :likes, only: [:create]
    
    resources :comments, only: [:create, :update, :destroy]
		
		resources :likes, only: [:destroy]
  end
  
  get 'auth/facebook/callback', to: 'sessions#create'

end

app/models/following.rb
class Following < ActiveRecord::Base

  validates :follower, uniqueness: { scope: :followee }

  belongs_to :follower,
              class_name: "User",
              foreign_key: :follower_id,
              primary_key: :id

  belongs_to :followee,
              class_name: "User",
              foreign_key: :followee_id,
              primary_key: :id
  
  has_many :notifications, as: :notifiable, inverse_of: :notifiable, dependent: :destroy
              
  after_commit :set_notification, on: [:create]
              
  
  def set_notification
    note = self.notifications.unread.event(:new_follower).new
    note.user = self.followee
    note.save

  end

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def new
    @following = Following.new
  end

  def create
    following = current_user.outbound_followings.new
    following.followee_id = params[:user_id]
    if following.save
    else
      flash.now[:errors] = following.errors.full_messages
    end
    redirect_to :back
  end

  def destroy
    following = current_user.outbound_followings.where("followee_id = ?", params[:id]).first
    following.destroy
    redirect_to current_user
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/layouts/following/_deletefollowee.html.erb
<form class="delete-followee group" action="<%= following_url(followee.id) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <%= auth_token %>
	<div class="submit group">
  	<input type="submit" value="&times;">
	</div>
</form>

app/views/layouts/following/_followers.html.erb
<ul class="my-followers">
	
	<% user.followers.each do |followee| %>
  
	  <li class="followee group">
			
		    <%= link_to followee.username, user_url(followee) %>

				<% if !current_user.people_he_follows.include?(followee) %>
				
					<form class="new-following-form" action="<%= user_followings_url(followee) %>" method="post">
					  <%= auth_token %>
							<div class="submit">
					    	<input type="submit" value="Follow">
							</div>

					</form>
				
				<% end %>
  			
	  </li>

	<% end %>
</ul>

app/views/layouts/following/_followings.html.erb
<ul class="group">
	
	<% user.people_he_follows.each do |followee| %>
  
	  <li class="followee group">
			
		    <%= link_to followee.username, user_url(followee) %>

				<% if @own_page %>
		    	<%= render partial: "layouts/following/deletefollowee", locals: {followee: followee}  %>
				<% end %>
  			
	  </li>

	<% end %>
</ul>

app/views/layouts/following/_new.html.erb
<form class="new-following-form" action="<%= user_followings_url(params["id"]) %>" method="post">
  <%= auth_token %>
		<div class="submit">
    	<input type="submit" value="Follow">
		</div>

</form>